import { Trade } from './types';

export const mockTrades: Trade[] = [
  {
    id: '1',
    date: '2026-05-20T09:30:00Z',
    asset: 'BTC/USD',
    market: 'Crypto',
    orderType: 'Long',
    entryPrice: 65000,
    exitPrice: 67500,
    positionSize: 0.5,
    fees: 15,
    takeProfit: 68000,
    stopLoss: 63000,
    grossPnl: 1250,
    netPnl: 1235,
    rrRatio: 1.5,
    percentageGain: 3.85,
    preTradeEmotion: 'Calm',
    postTradeEmotion: 'Disciplined',
    disciplineRating: 5,
    notes: 'Followed the setup perfectly. Market was trending up.',
    marketSentiment: 'Bullish',
    mistakeTags: [],
  },
  {
    id: '2',
    date: '2026-05-21T14:15:00Z',
    asset: 'ETH/USD',
    market: 'Crypto',
    orderType: 'Short',
    entryPrice: 3500,
    exitPrice: 3600,
    positionSize: 10,
    fees: 12,
    takeProfit: 3200,
    stopLoss: 3600,
    grossPnl: -1000,
    netPnl: -1012,
    rrRatio: 1.0,
    percentageGain: -2.86,
    preTradeEmotion: 'Fearful of Missing Out',
    postTradeEmotion: 'Frustrated',
    disciplineRating: 2,
    notes: 'Chased the pump, got stopped out quickly. Need to be more patient.',
    marketSentiment: 'Choppy',
    newsCatalyst: 'CPI Release',
    mistakeTags: ['#FOMO', '#ChasedThePump'],
  },
  {
    id: '3',
    date: '2026-05-22T10:00:00Z',
    asset: 'TSLA',
    market: 'Stocks',
    orderType: 'Long',
    entryPrice: 180,
    exitPrice: 195,
    positionSize: 100,
    fees: 2,
    takeProfit: 200,
    stopLoss: 170,
    grossPnl: 1500,
    netPnl: 1498,
    rrRatio: 2.0,
    percentageGain: 8.33,
    preTradeEmotion: 'Confident',
    postTradeEmotion: 'Relieved',
    disciplineRating: 4,
    notes: 'Good bounce off support. Took profits a bit early.',
    marketSentiment: 'Bullish',
    mistakeTags: ['#EarlyExit'],
  },
  {
    id: '4',
    date: '2026-05-23T08:45:00Z',
    asset: 'EUR/USD',
    market: 'Forex',
    orderType: 'Short',
    entryPrice: 1.0850,
    exitPrice: 1.0800,
    positionSize: 100000,
    fees: 5,
    takeProfit: 1.0750,
    stopLoss: 1.0900,
    grossPnl: 500,
    netPnl: 495,
    rrRatio: 1.0,
    percentageGain: 0.46,
    preTradeEmotion: 'Calm',
    postTradeEmotion: 'Disciplined',
    disciplineRating: 5,
    notes: 'Textbook rejection at resistance.',
    marketSentiment: 'Bearish',
    mistakeTags: [],
  }
];

// Helper to generate cumulative PnL data for the chart
export const generatePnlData = () => {
  let cumulative = 10000; // Starting account balance
  return mockTrades.map(trade => {
    cumulative += trade.netPnl;
    return {
      date: new Date(trade.date).toLocaleDateString(),
      balance: cumulative,
      netPnl: trade.netPnl
    };
  });
};
